# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

provider "google" {
  default_labels = {
    goog-adc-tf-deployment = "export"
  }
  billing_project       = "agentverseaiprojectdevfest"
  user_project_override = true
}
provider "google-beta" {
  default_labels = {
    goog-adc-tf-deployment = "export"
  }
  billing_project       = "agentverseaiprojectdevfest"
  user_project_override = true
}


terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 5.32.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = ">= 5.32.0"
    }
  }
}
