steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/storygen/storygen-backend:$COMMIT_SHA",
        ".",
      ]

  # Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/storygen/storygen-backend:$COMMIT_SHA",
      ]

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "storygen-backend-${_ENV}",
        "--image",
        "us-central1-docker.pkg.dev/$PROJECT_ID/storygen/storygen-backend:$COMMIT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "8080",
      ]

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/storygen/storygen-backend:$COMMIT_SHA"

substitutions:
  _ENV: "staging"

options:
  logging: CLOUD_LOGGING_ONLY
